# -*- coding: utf-8 -*-
"""3D_visualization_of_BigData.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mcOFpDsRwqRXPkaY8t2cIo1QprXfdyNs

The exclamation mark "!" is used in Jupyter Notebook (or Google Colab) to run shell commands.

"pip install" -
pip is Python’s package manager.
"install" tells pip to download and install the listed Python packages from the Python Package Index (PyPI).

"pydeck" -
A Python wrapper for deck.gl, which is a powerful WebGL-based visualization library for geospatial data. It allows to create interactive maps and 3D visualizations inside Jupyter notebooks or web apps.

"geopandas" -
Extends pandas to support geospatial data (data with geometry like points, lines, and polygons). Makes it easy to load, analyze, and plot spatial data such as shapefiles or GeoJSON. (https://geopandas.org/en/stable/about.html)

"pandas" -
A core data analysis library for Python. Provides powerful tools for working with tabular data (DataFrames and Series). Used for cleaning, analyzing, and transforming datasets. (https://pandas.pydata.org/about/index.html)
"""

!pip install pydeck geopandas pandas

""""import pydeck as pdk" - Loads the pydeck library (for interactive map visualization) and gives it the short alias pdk.

"import pandas as pd" - Loads pandas (for data handling and analysis) and gives it the standard alias pd.

"import geopandas as gpd" - Loads geopandas (for geospatial data analysis) and gives it the alias gpd.
"""

import pydeck as pdk
import pandas as pd
import geopandas as gpd

"""This line of code stores the online location of a dataset so we can later load it directly into Python.

"""

DATA_URL = "https://raw.githubusercontent.com/ajduberstein/sf_public_data/master/bay_area_commute_routes.csv"

"""This line downloads the CSV file from the URL and loads it into a pandas DataFrame named df, so we can analyze or visualize the data easily in Python."""

df = pd.read_csv(DATA_URL)

"""DOWNTOWN_BOUNDING_BOX - A variable name that stores geographic coordinates defining a rectangular area (a bounding box) around downtown San Francisco."""

DOWNTOWN_BOUNDING_BOX = [
    -122.43135291617365,
    37.766492914983864,
    -122.38706428091974,
    37.80583561830737,
]

"""This function checks whether a geographic point (longitude, latitude) lies inside the downtown San Francisco bounding box defined earlier."""

def in_bounding_box(lng, lat):
    return (DOWNTOWN_BOUNDING_BOX[0] <= lng <= DOWNTOWN_BOUNDING_BOX[2] and
            DOWNTOWN_BOUNDING_BOX[1] <= lat <= DOWNTOWN_BOUNDING_BOX[3])

""""df.apply(..., axis=1)" -
Applies a function to each row of the DataFrame.

"axis=1' means apply across columns for each row.

"lambda row: in_bounding_box(row["lng_w"], row["lat_w"])" -
Defines a small anonymous function that:
Takes each row.
Calls in_bounding_box() using the worker’s longitude (lng_w) and latitude (lat_w).
Returns True if the worker location is inside the downtown box.

"lambda row: in_bounding_box(row["lng_h"], row["lat_h"])" -
Does the same for the home location coordinates (lng_h, lat_h).

"& (bitwise AND)" -
Combines both Boolean results.
"""

df = df[df.apply(lambda row: in_bounding_box(row["lng_w"], row["lat_w"]), axis=1)
        & df.apply(lambda row: in_bounding_box(row["lng_h"], row["lat_h"]), axis=1)]

"""These define colors for map layers in pydeck or other visualization tools, including transparency so overlapping routes can be seen."""

GREEN = [0, 255, 0, 40]
RED = [240, 100, 0, 40]

"""Creates a pydeck Layer called arc_layer that visualizes arcs (curved lines) between two points: home - work.

"ArcLayer" -
Specifies the type of layer.

"data=df" -
The dataset to visualize (pandas DataFrame with home/work coordinates).

"get_source_position=["lng_h", "lat_h"]" -
Specifies home location as the starting point of each arc.

"get_target_position=["lng_w", "lat_w"]" -
Specifies work location as the ending point of each arc.

"get_source_color=RED" -
Color of the arc at the source (home) end.

"get_target_color=GREEN" -
Color of the arc at the target (work) end.
Creates a gradient from RED → GREEN along the arc.

"get_width="S000 * 2"" -
Determines the thickness of each arc.
Uses the dataset column "S000" and multiplies it by 2.
This could represent volume or intensity of commutes.

"get_tilt=15" -
Tilts the arcs in 3D for better visual effect on the map.

"pickable=True" -
Allows interaction: you can click or hover on arcs to get info.

"auto_highlight=True" -
Highlights an arc when you hover over it, making it visually stand out.
"""

arc_layer = pdk.Layer(
    "ArcLayer",
    data=df,
    get_source_position=["lng_h", "lat_h"],   # home (source) position
    get_target_position=["lng_w", "lat_w"],   # work (destination) position
    get_source_color=RED,
    get_target_color=GREEN,
    get_width="S000 * 2",   # width accessor: uses a column named "S000" from the dataset
    get_tilt=15,
    pickable=True,
    auto_highlight=True,
)

"""This line sets how the map is positioned and oriented when it is first rendered:

1.Centered around San Francisco,

2.Zoomed moderately,

3.Rotated 45° clockwise,

4.Tilted 50° for a 3D perspective.

5.It works together with the arc_layer to display an interactive 3D map.
"""

view_state = pdk.ViewState(
    latitude=37.7576171,
    longitude=-122.5776844,
    zoom=8,
    bearing=45,
    pitch=50
)

"""Tooltips appear when you hover over an arc on the map, showing additional information.

"html": "{S000} jobs <br> Home location (red) - Work location (green)" -
1.HTML string for the tooltip content.

2.{S000} -  placeholder that will be replaced by the value from the "S000" column in your DataFrame for that row.

3.br - line break in HTML.

4.Gives information like number of jobs and the direction of commute.


"style": {"color": "white"} -
1.CSS styling for the tooltip text.

2.Sets the text color to white for better visibility on a dark map background.
"""

tooltip = {
    "html": "{S000} jobs <br> Home location (red) → Work location (green)",
    "style": {"color": "white"},
}

"""Creates a pydeck map object called deck that combines your data layer, map view, and interactive tooltip.

"layers=[arc_layer]" -
Here, it includes only the arc_layer that shows arcs between home and work.

"initial_view_state=view_state" -
Defines the starting position, zoom, rotation, and tilt of the map.

"tooltip=tooltip" -
Adds interactive tooltips for each arc.
"""

deck = pdk.Deck(
    layers=[arc_layer],
    initial_view_state=view_state,
    tooltip=tooltip,
)

""""deck.to_html("arc_layer_map.html", notebook_display=True)" - Export your pydeck map to a standalone HTML file.

"deck.show()" - Display the map interactively.


"""

deck.to_html("arc_layer_map.html", notebook_display=True)
deck.show()

from google.colab import files
files.download("arc_layer_map.html")