# -*- coding: utf-8 -*-
"""MarkerCluster.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GU8Zm1953wSU7J-s32rd6bLSUH-0J5Pn
"""

!pip install leafmap

import leafmap

map = leafmap.Map()
map

Rail_stations = "https://raw.githubusercontent.com/Shreenitya/nitya/refs/heads/main/tamilnadu_railwaystations.csv"

map.add_points_from_xy(Rail_stations, x = "Latitude", y="Longitude", layer_name="Rail_stations")
map