# -*- coding: utf-8 -*-
"""Point_cloud_visualization_with pydeck_package.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bxvMD_OXaTmtkjptsdvFQictQIQ1VM0o

! (Exclamation mark) -
This tells environments like Jupyter Notebook, Google Colab that the following command should be run in the system shell, not in Python itself.

pip -
pip stands for “Pip Installs Packages”.
It’s the default Python package manager, used to install and manage software packages written in Python.

pydeck -
pydeck is a Python library for 3D map visualization, built on top of Deck.gl (a powerful WebGL-based visualization framework created by Uber).
It integrates nicely with Jupyter Notebooks and supports maps, scatter plots, hexagon layers, and more — useful for geospatial data visualization.
"""

!pip install pydeck

"""importing pydeck and giving it a alias as pdk so that everytime we don't have to type pydeck instead we can type pdk"""

import pydeck as pdk
import pandas as pd

"""Taking data in csv format from github and giving it's raw url"""

data_url = "https://raw.githubusercontent.com/ajduberstein/geo_datasets/master/small_waterfall.csv"

"""read_csv() is a pandas function that reads a CSV (Comma-Separated Values) file and converts it into a DataFrame.

A DataFrame is like a spreadsheet or table — it has rows and columns.

read_csv() can read CSV data from:
A local file ,
A web URL
"""

df = pd.read_csv(data_url)

""" "PointCloudLayer" - This tells Pydeck what kind of visualization layer to use, here it’s a 3D point cloud. Each data point becomes a 3D dot.

data - df	Uses the pandas DataFrame (df) as the source of the data. The DataFrame must have columns named x, y, z, r, g, b.

get_position - ["x", "y", "z"]	Tells Pydeck which columns in df represent 3D coordinates. Each row gives one point’s (x, y, z) position.

get_color - ["r", "g", "b"]	Tells Pydeck which columns define color (Red, Green, Blue) values for each point.

get_normal - [0, 0, 15]	Defines the normal vector for lighting, the direction light comes from, which affects how the 3D points are shaded.

point_size - 1	Controls how big each point is. Increasing this makes points larger and more visible.

pickable - True	Makes the points interactive ,we can hover or click them to see data tooltips.

auto_highlight - True	Highlights a point automatically when we hover over it.
"""

point_cloud = pdk.Layer(
    "PointCloudLayer",
    data=df,
    get_position=["x", "y", "z"],
    get_color=["r", "g", "b"],
    get_normal=[0, 0, 15],
    point_size=1,
    pickable=True,
    auto_highlight=True,
)

"""target - [df.x.mean(), df.y.mean(), df.z.mean()]	Centers the view around the average position of all your points, so it will be looking at the middle of the cloud.

rotation_x - 15	Rotates the view 15° around the X-axis, so it will be looking at the 3D data from a tilted angle.

rotation_orbit - 30	Rotates the view 30° around the vertical axis, giving a nice diagonal perspective.

zoom - 5	Sets the zoom level higher means closer.

controller - True	Allows you to drag, zoom, and orbit interactively with your mouse.
"""

view = pdk.ViewState(
    target=[df.x.mean(), df.y.mean(), df.z.mean()],
    rotation_x=15,
    rotation_orbit=30,
    zoom=5,
    controller=True,
)

""""OrbitView" is a 3D camera type that lets you orbit around the scene (rotate and zoom freely).
It’s perfect for 3D visualizations like point clouds.

controller - True again means you can interact with the view using your mouse.

pdk.Deck(...)	The main visualization container. It takes the layers, initial camera state, and view settings and prepares everything for rendering.

layers - [point_cloud]	Adds the 3D layer to the deck. We can include multiple layers (for example, point clouds + polygons + text labels).

initial_view_state - view	Sets the starting camera position and rotation.

views - [view1]	Specifies which view type (OrbitView) to use.

deck.to_html("point_cloud.html") - Save the deck as an HTML file

deck.show()	Displays the visualization right in the notebook.
"""

view1 = pdk.View(type="OrbitView", controller=True)
deck = pdk.Deck(layers=[point_cloud], initial_view_state=view, views=[view1])
deck.to_html("point_cloud.html") # Save the deck as an HTML file
deck.show()

"""from google.colab import files -
This imports the files module from the google.colab package.

files.download("point_cloud.html") -
This command downloads a file from the Colab session (the temporary virtual machine environment) to local computer.
"""

from google.colab import files
files.download("point_cloud.html")