# -*- coding: utf-8 -*-
"""Practical3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1n6k-gFziHJcMdzESGlWM7yLAxwVhres_
"""

pip install geemap

pip install geemap[all]

pip install geemap[lidar]

pip install geemap[raster]

pip install geemap[sql]

pip install geemap[vector]

pip install geemap[streamlit]

import geemap.geemap as map

import ee

ee.Authenticate()

ee.Initialize(project='shreenitya0428')

m=map.Map()
m

India = ee.FeatureCollection('projects/shreenitya0428/assets/India_states')
India

India_districts = ee.FeatureCollection('projects/shreenitya0428/assets/India_districts')
m.addLayer(India_districts,{},'India_districts')
m

Chandigarh = India_districts.filter(ee.Filter.eq('STATE','CHAND|GARH'))
m.addLayer(Chandigarh,{},'Chandigarh')
m

NDVI2024 = ee.ImageCollection("LANDSAT/COMPOSITES/C02/T1_L2_8DAY_NDVI").select('NDVI').filterDate('2024-03-01', '2024-12-31')
ChandigarhNDVI_2024 = NDVI2024.mean().clip(Chandigarh)
NDVI = {'min':0, 'max':1, 'palette': ['ffffff', 'ce7e45', 'df923d', 'f1b555', 'fcd163', '99b718', '74a901',
    '66a000', '529400', '3e8601', '207401', '056201', '004c00', '023b01',
    '012e01', '011d01', '011301']}
m.addLayer(ChandigarhNDVI_2024, NDVI, 'NDVI_2024')
m

import os

Chandigarh_clipped = ChandigarhNDVI_2024.clip(Chandigarh.geometry())
out_dir = os.path.join(os.path.expanduser('~'), 'Downloads')
filename = os.path.join(out_dir, 'NDVI_2024.tif')
if not os.path.exists(out_dir):
    os.makedirs(out_dir)
map.ee_export_image(
    Chandigarh_clipped,
    filename=filename,
    scale=30,
    region=Chandigarh.geometry(),
    file_per_band=False
)

NDVI2014 = ee.ImageCollection("LANDSAT/COMPOSITES/C02/T1_L2_8DAY_NDVI").select('NDVI').filterDate('2014-03-01', '2014-5-31')
ChandigarhNDVI_2014 = NDVI2014.mean().clip(Chandigarh)
ChandigarhNDVI_2014 = ChandigarhNDVI_2014.updateMask(ChandigarhNDVI_2014.gt(0))
NDVI = {'min':0, 'max':1, 'palette': ['ffffff', 'ce7e45', 'df923d', 'f1b555', 'fcd163', '99b718', '74a901',
    '66a000', '529400', '3e8601', '207401', '056201', '004c00', '023b01',
    '012e01', '011d01', '011301']}
m.addLayer(ChandigarhNDVI_2014, NDVI, 'NDVI_2014')
m

Chandigarh_clipped = ChandigarhNDVI_2014.clip(Chandigarh.geometry())
out_dir = os.path.join(os.path.expanduser('~'), 'Downloads')
filename = os.path.join(out_dir, 'NDVI_2014.tif')
if not os.path.exists(out_dir):
    os.makedirs(out_dir)
map.ee_export_image(
    Chandigarh_clipped,
    filename=filename,
    scale=30,
    region=Chandigarh.geometry(),
    file_per_band=False
)

NDVI2004 = ee.ImageCollection("LANDSAT/COMPOSITES/C02/T1_L2_8DAY_NDVI").select('NDVI').filterDate('2004-03-01', '2004-5-31')
ChandigarhNDVI_2004 = NDVI2004.mean().clip(Chandigarh)
ChandigarhNDVI_2004 = ChandigarhNDVI_2004.updateMask(ChandigarhNDVI_2004.gt(0))
NDVI = {'min':0, 'max':1, 'palette': ['ffffff', 'ce7e45', 'df923d', 'f1b555', 'fcd163', '99b718', '74a901',
    '66a000', '529400', '3e8601', '207401', '056201', '004c00', '023b01',
    '012e01', '011d01', '011301']}
m.addLayer(ChandigarhNDVI_2004, NDVI, 'NDVI_2004')
m

Chandigarh_clipped = ChandigarhNDVI_2004.clip(Chandigarh.geometry())
out_dir = os.path.join(os.path.expanduser('~'), 'Downloads')
filename = os.path.join(out_dir, 'NDVI_2004.tif')
if not os.path.exists(out_dir):
    os.makedirs(out_dir)
map.ee_export_image(
    Chandigarh_clipped,
    filename=filename,
    scale=30,
    region=Chandigarh.geometry(),
    file_per_band=False
)

NDVI1994 = ee.ImageCollection("LANDSAT/COMPOSITES/C02/T1_L2_8DAY_NDVI").select('NDVI').filterDate('1994-03-01', '1994-5-31')
ChandigarhNDVI_1994 = NDVI1994.mean().clip(Chandigarh)
ChandigarhNDVI_1994 = ChandigarhNDVI_1994.updateMask(ChandigarhNDVI_1994.gt(0))
NDVI = {'min':0, 'max':1, 'palette': ['ffffff', 'ce7e45', 'df923d', 'f1b555', 'fcd163', '99b718', '74a901',
    '66a000', '529400', '3e8601', '207401', '056201', '004c00', '023b01',
    '012e01', '011d01', '011301']}
m.addLayer(ChandigarhNDVI_1994, NDVI, 'NDVI_1994')
m

Chandigarh_clipped = ChandigarhNDVI_1994.clip(Chandigarh.geometry())
out_dir = os.path.join(os.path.expanduser('~'), 'Downloads')
filename = os.path.join(out_dir, 'NDVI_1994.tif')
if not os.path.exists(out_dir):
    os.makedirs(out_dir)
map.ee_export_image(
    Chandigarh_clipped,
    filename=filename,
    scale=30,
    region=Chandigarh.geometry(),
    file_per_band=False
)

NDVI1989 = ee.ImageCollection("LANDSAT/COMPOSITES/C02/T1_L2_8DAY_NDVI").select('NDVI').filterDate('1989-03-01', '1989-12-31')
ChandigarhNDVI_1989= NDVI1989.mean().clip(Chandigarh)
NDVI = {'min':0, 'max':1, 'palette': ['ffffff', 'ce7e45', 'df923d', 'f1b555', 'fcd163', '99b718', '74a901',
    '66a000', '529400', '3e8601', '207401', '056201', '004c00', '023b01',
    '012e01', '011d01', '011301']}
m.addLayer(ChandigarhNDVI_1989, NDVI, 'NDVI_1989')
m

Chandigarh_clipped = ChandigarhNDVI_1989.clip(Chandigarh.geometry())
out_dir = os.path.join(os.path.expanduser('~'), 'Downloads')
filename = os.path.join(out_dir, 'NDVI_1989.tif')
if not os.path.exists(out_dir):
    os.makedirs(out_dir)
map.ee_export_image(
    Chandigarh_clipped,
    filename=filename,
    scale=30,
    region=Chandigarh.geometry(),
    file_per_band=False
)

def calculate_NDWI(image):
    green = image.select('SR_B3')
    nir = image.select('SR_B5')
    ndwi = green.subtract(nir).divide(green.add(nir)).rename('NDWI')
    return image.addBands(ndwi)
NDWI2024 = (
    ee.ImageCollection("LANDSAT/LC09/C02/T1_L2")
    .filterDate('2024-03-01', '2024-05-31')
    .filterBounds(Chandigarh)
    .map(calculate_NDWI)
)
ChandigarhNDWI_2024 = NDWI2024.select('NDWI').mean().clip(Chandigarh)
NDWI_viz = {'min': -1, 'max': 1, 'palette': [
        '#D73027',  # Red (Dry/Built-up)
        '#FC8D59',  # Orange (Barren Land)
        '#FEE08B',  # Yellow (Sparse Vegetation)
        '#D9EF8B',  # Light Green (Moist Soil)
        '#91CF60',  # Green (Vegetation)
        '#1A9850',  # Dark Green (Shallow Water)
        '#313695'   # Blue (Deep Water)
    ]}
m.addLayer(ChandigarhNDWI_2024, NDWI_viz, 'NDWI_2024')
m

Chandigarh_clipped = ChandigarhNDWI_2024.clip(Chandigarh.geometry())
out_dir = os.path.join(os.path.expanduser('~'), 'Downloads')
filename = os.path.join(out_dir, 'NDWI_2024.tif')
if not os.path.exists(out_dir):
    os.makedirs(out_dir)
map.ee_export_image(
    Chandigarh_clipped,
    filename=filename,
    scale=30,
    region=Chandigarh.geometry(),
    file_per_band=False
)

def calculate_NDWI(image):
    green = image.select('SR_B3')
    nir = image.select('SR_B5')
    ndwi = green.subtract(nir).divide(green.add(nir)).rename('NDWI')
    return image.addBands(ndwi)
NDWI2014 = (
    ee.ImageCollection("LANDSAT/LC08/C02/T1_L2")
    .filterDate('2014-03-01', '2014-05-31')
    .filterBounds(Chandigarh)
    .map(calculate_NDWI)
)
ChandigarhNDWI_2014 = NDWI2014.select('NDWI').mean().clip(Chandigarh)
NDWI_viz = {'min': -1, 'max': 1, 'palette': [
        '#D73027',  # Red (Dry/Built-up)
        '#FC8D59',  # Orange (Barren Land)
        '#FEE08B',  # Yellow (Sparse Vegetation)
        '#D9EF8B',  # Light Green (Moist Soil)
        '#91CF60',  # Green (Vegetation)
        '#1A9850',  # Dark Green (Shallow Water)
        '#313695'   # Blue (Deep Water)
    ]}
m.addLayer(ChandigarhNDWI_2014, NDWI_viz, 'NDWI_2014')
m

Chandigarh_clipped = ChandigarhNDWI_2014.clip(Chandigarh.geometry())
out_dir = os.path.join(os.path.expanduser('~'), 'Downloads')
filename = os.path.join(out_dir, 'NDWI_2014.tif')
if not os.path.exists(out_dir):
    os.makedirs(out_dir)
map.ee_export_image(
    Chandigarh_clipped,
    filename=filename,
    scale=30,
    region=Chandigarh.geometry(),
    file_per_band=False
)

def calculate_NDWI(image):
    green = image.select('SR_B2')
    nir = image.select('SR_B4')
    ndwi = green.subtract(nir).divide(green.add(nir)).rename('NDWI')
    return image.addBands(ndwi)
NDWI2004 = (
    ee.ImageCollection("LANDSAT/LT05/C02/T1_L2")
    .filterDate('2004-03-01', '2004-05-31')
    .filterBounds(Chandigarh)
    .map(calculate_NDWI)
)
ChandigarhNDWI_2004 = NDWI2004.select('NDWI').mean().clip(Chandigarh)
NDWI_viz = {'min': -1, 'max': 1, 'palette': [
        '#D73027',  # Red (Dry/Built-up)
        '#FC8D59',  # Orange (Barren Land)
        '#FEE08B',  # Yellow (Sparse Vegetation)
        '#D9EF8B',  # Light Green (Moist Soil)
        '#91CF60',  # Green (Vegetation)
        '#1A9850',  # Dark Green (Shallow Water)
        '#313695'   # Blue (Deep Water)
    ]}
m.addLayer(ChandigarhNDWI_2004, NDWI_viz, 'NDWI_2004')
m

# Chandigarh_clipped = ChandigarhNDWI_2004.clip(Chandigarh.geometry())
# out_dir = os.path.join(os.path.expanduser('~'), 'Downloads')
# filename = os.path.join(out_dir, 'NDWI_2004.tif')
# if not os.path.exists(out_dir):
#     os.makedirs(out_dir)
# map.ee_export_image(
#     Chandigarh_clipped,
#     filename=filename,
#     scale=30,
#     region=Chandigarh.geometry(),
#     file_per_band=False
# )

def calculate_NDWI(image):
    green = image.select('SR_B2')
    nir = image.select('SR_B4')
    ndwi = green.subtract(nir).divide(green.add(nir)).rename('NDWI')
    return image.addBands(ndwi)
NDWI1994 = (
    ee.ImageCollection("LANDSAT/LT05/C02/T1_L2")
    .filterDate('1994-03-01', '1994-05-31')
    .filterBounds(Chandigarh)
    .map(calculate_NDWI)
)
ChandigarhNDWI_1994 = NDWI1994.select('NDWI').mean().clip(Chandigarh)
NDWI_viz = {'min': -1, 'max': 1, 'palette': [
        '#D73027',  # Red (Dry/Built-up)
        '#FC8D59',  # Orange (Barren Land)
        '#FEE08B',  # Yellow (Sparse Vegetation)
        '#D9EF8B',  # Light Green (Moist Soil)
        '#91CF60',  # Green (Vegetation)
        '#1A9850',  # Dark Green (Shallow Water)
        '#313695'   # Blue (Deep Water)
    ]}
m.addLayer(ChandigarhNDWI_1994, NDWI_viz, 'NDWI_1994')
m

Chandigarh_clipped = ChandigarhNDWI_1994.clip(Chandigarh.geometry())
out_dir = os.path.join(os.path.expanduser('~'), 'Downloads')
filename = os.path.join(out_dir, 'NDWI_1994.tif')
if not os.path.exists(out_dir):
    os.makedirs(out_dir)
map.ee_export_image(
    Chandigarh_clipped,
    filename=filename,
    scale=30,
    region=Chandigarh.geometry(),
    file_per_band=False
)

def calculate_NDWI(image):
    green = image.select('SR_B2')
    nir = image.select('SR_B4')
    ndwi = green.subtract(nir).divide(green.add(nir)).rename('NDWI')
    return image.addBands(ndwi)
NDWI1989 = (
    ee.ImageCollection("LANDSAT/LT05/C02/T1_L2")
    .filterDate('1989-04-01', '1989-12-31')
    .filterBounds(Chandigarh)
    .map(calculate_NDWI)
)
ChandigarhNDWI_1989 = NDWI1989.select('NDWI').mean().clip(Chandigarh)
NDWI_viz = {'min': -1, 'max': 1, 'palette': [
        '#D73027',  # Red (Dry/Built-up)
        '#FC8D59',  # Orange (Barren Land)
        '#FEE08B',  # Yellow (Sparse Vegetation)
        '#D9EF8B',  # Light Green (Moist Soil)
        '#91CF60',  # Green (Vegetation)
        '#1A9850',  # Dark Green (Shallow Water)
        '#313695'   # Blue (Deep Water)
    ]}
m.addLayer(ChandigarhNDWI_1989, NDWI_viz, 'NDWI_1989')
m

Chandigarh_clipped = ChandigarhNDWI_1989.clip(Chandigarh.geometry())
out_dir = os.path.join(os.path.expanduser('~'), 'Downloads')
filename = os.path.join(out_dir, 'NDWI_1989.tif')
if not os.path.exists(out_dir):
    os.makedirs(out_dir)
map.ee_export_image(
    Chandigarh_clipped,
    filename=filename,
    scale=30,
    region=Chandigarh.geometry(),
    file_per_band=False
)

def calculate_SAVI(image):
    nir = image.select('SR_B5')
    red = image.select('SR_B4')
    L = 0.5

    savi = nir.subtract(red).multiply(1 + L).divide(nir.add(red).add(L)).rename('SAVI')
    return image.addBands(savi)

SAVI2024 = (
    ee.ImageCollection("LANDSAT/LC08/C02/T1_L2")
    .filterDate('2024-03-01', '2024-05-31')
    .filterBounds(Chandigarh)
    .map(calculate_SAVI)
)

ChandigarhSAVI_2024 = SAVI2024.select('SAVI').mean().clip(Chandigarh)

SAVI_viz = {
    'min': -1,
    'max': 1,
    'palette': [
        'brown',    # Barren land / soil
        'yellow',   # Sparse vegetation
        'lightgreen', # Moderate vegetation
        'green',    # Dense vegetation
        'darkgreen' # Very dense vegetation
    ]
}

m.addLayer(ChandigarhSAVI_2024, SAVI_viz, 'SAVI_2024')
m

Chandigarh_clipped = ChandigarhSAVI_2024.clip(Chandigarh.geometry())
out_dir = os.path.join(os.path.expanduser('~'), 'Downloads')
filename = os.path.join(out_dir, 'SAVI_2024.tif')
if not os.path.exists(out_dir):
    os.makedirs(out_dir)
map.ee_export_image(
    Chandigarh_clipped,
    filename=filename,
    scale=30,
    region=Chandigarh.geometry(),
    file_per_band=False
)

def calculate_SAVI(image):
    nir = image.select('SR_B5')
    red = image.select('SR_B4')
    L = 0.5

    savi = nir.subtract(red).multiply(1 + L).divide(nir.add(red).add(L)).rename('SAVI')
    return image.addBands(savi)

SAVI2014 = (
    ee.ImageCollection("LANDSAT/LC08/C02/T1_L2")
    .filterDate('2014-03-01', '2014-05-31')
    .filterBounds(Chandigarh)
    .map(calculate_SAVI)
)

ChandigarhSAVI_2014 = SAVI2014.select('SAVI').mean().clip(Chandigarh)

SAVI_viz = {
    'min': -1,  # Lower bound for SAVI values
    'max': 1,   # Upper bound for SAVI values
    'palette': [
        'brown',    # Barren land / soil
        'yellow',   # Sparse vegetation
        'lightgreen', # Moderate vegetation
        'green',    # Dense vegetation
        'darkgreen' # Very dense vegetation
    ]
}

m.addLayer(ChandigarhSAVI_2014, SAVI_viz, 'SAVI_2014')
m

Chandigarh_clipped = ChandigarhSAVI_2014.clip(Chandigarh.geometry())
out_dir = os.path.join(os.path.expanduser('~'), 'Downloads')
filename = os.path.join(out_dir, 'SAVI_2014.tif')
if not os.path.exists(out_dir):
    os.makedirs(out_dir)
map.ee_export_image(
    Chandigarh_clipped,
    filename=filename,
    scale=30,
    region=Chandigarh.geometry(),
    file_per_band=False
)

def calculate_SAVI(image):
    nir = image.select('SR_B4')
    red = image.select('SR_B3')
    L = 0.5

    savi = nir.subtract(red).multiply(1 + L).divide(nir.add(red).add(L)).rename('SAVI')
    return image.addBands(savi)

SAVI2004 = (
    ee.ImageCollection("LANDSAT/LT05/C02/T1_L2")
    .filterDate('2004-03-01', '2004-05-31')
    .filterBounds(Chandigarh)
    .map(calculate_SAVI)
)

ChandigarhSAVI_2004 = SAVI2004.select('SAVI').mean().clip(Chandigarh)

SAVI_viz = {
    'min': -1,  # Lower bound for SAVI values
    'max': 1,   # Upper bound for SAVI values
    'palette': [
        'brown',    # Barren land / soil
        'yellow',   # Sparse vegetation
        'lightgreen', # Moderate vegetation
        'green',    # Dense vegetation
        'darkgreen' # Very dense vegetation
    ]
}

m.addLayer(ChandigarhSAVI_2004, SAVI_viz, 'SAVI_2004')
m

Chandigarh_clipped = ChandigarhSAVI_2004.clip(Chandigarh.geometry())
out_dir = os.path.join(os.path.expanduser('~'), 'Downloads')
filename = os.path.join(out_dir, 'SAVI_2004.tif')
if not os.path.exists(out_dir):
    os.makedirs(out_dir)
map.ee_export_image(
    Chandigarh_clipped,
    filename=filename,
    scale=30,
    region=Chandigarh.geometry(),
    file_per_band=False
)

def calculate_SAVI(image):
    nir = image.select('SR_B4')
    red = image.select('SR_B3')
    L = 0.5

    savi = nir.subtract(red).multiply(1 + L).divide(nir.add(red).add(L)).rename('SAVI')
    return image.addBands(savi)

SAVI1994 = (
    ee.ImageCollection("LANDSAT/LT05/C02/T1_L2")
    .filterDate('1994-03-01', '1994-05-31')
    .filterBounds(Chandigarh)
    .map(calculate_SAVI)
)

ChandigarhSAVI_1994 = SAVI1994.select('SAVI').mean().clip(Chandigarh)

SAVI_viz = {
    'min': -1,
    'max': 1,
    'palette': [
        'brown',    # Barren land / soil
        'yellow',   # Sparse vegetation
        'lightgreen', # Moderate vegetation
        'green',    # Dense vegetation
        'darkgreen' # Very dense vegetation
    ]
}

m.addLayer(ChandigarhSAVI_1994, SAVI_viz, 'SAVI_1994')
m

Chandigarh_clipped = ChandigarhSAVI_1994.clip(Chandigarh.geometry())
out_dir = os.path.join(os.path.expanduser('~'), 'Downloads')
filename = os.path.join(out_dir, 'SAVI_1994.tif')
if not os.path.exists(out_dir):
    os.makedirs(out_dir)
map.ee_export_image(
    Chandigarh_clipped,
    filename=filename,
    scale=30,
    region=Chandigarh.geometry(),
    file_per_band=False
)

m.setCenter(78.486671, 17.385044, 10)

out_dir = 'Downloads'
filename_html = os.path.join(out_dir, 'NDVI_SAVI_NDWI_map.html')

if not os.path.exists(out_dir):
    os.makedirs(out_dir)
m.save('/content/Downloads/NDVI_SAVI_NDWI_map.html')

from google.colab import files
files.download('/content/Downloads/NDVI_SAVI_NDWI_map.html')